#!/bin/sh
echo "Waiting 5 seconds..."
sleep 5
echo "raspberry" | sudo -S mkdir /mnt/log/
echo "raspberry" | sudo -S mount /dev/sda1 /mnt/log/
exec env LD_LIBRARY_PATH=/usr/local/frc/lib java -jar uploaded.jar
