name: Javadoc

on: [push]
#on:
#  push:
#    branches:
#      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate Javadoc
        run: ./gradlew javadoc
      - name: Deploy Processing Docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          FOLDER: Processing/build/docs/javadoc
          TARGET_FOLDER: javadoc/*
